---
title: "Untitled"
format: html
editor: visual
---

------------------------------------------------------------------------

------------------------------------------------------------------------

```{r load-packages, echo = FALSE, message = FALSE, warning = FALSE}
library(shiny)
library(rmapshaper)
library(DT)
library(sf)
library(htmltools)
library(leafsync)
library(kableExtra)
library(tidyverse)
library(leaflet)
library(ggthemes)
library(ggridges)
library(ggmap)
library(lubridate)
library(stringr)
library(readr)
library(broom)
library(RColorBrewer)
library(forcats)
library(colorspace)
library(visdat)
library(naniar)
library(ggrepel)
library(styler)
library(lintr)
library(tidycensus)
library(gt)
library(sf)
library(viridis)
library(terra)
library(ncdf4)
nc <- nc_open("~/FishyG/data/Global_weather/PNWNamet_tasmax.nc.nc")
print(nc)

river_coords <- read_csv("~/FishyG/data/survey_sites_vancouver_isl.csv", show_col_types = FALSE)

describe("~/FishyG/data/Global_weather/PNWNamet_tasmax.nc.nc")

tasmax <- rast("~/FishyG/data/Global_weather/PNWNamet_tasmax.nc.nc")

weather <- "~/FishyG/data/Global_weather/merged_tavg_prcp_1960_2025.nc"

```

```{r}
river_coords <- river_coords %>%
  mutate(model = case_when(
    stream_name_pse %in% c("NANAIMO RIVER", "COWICHAN RIVER", "LITTLE QUALICUM RIVER", "CHEMAINUS RIVER") ~ "Model", TRUE ~"No model"
  ))
```

```{r}
tavg <- rast(weather, subds = "tavg")
pr <- rast(weather, subds = "pr")

yrs_t <- format(time(tavg),   "%Y")
yrs_p <- format(time(pr),   "%Y")
```

```{r}

tavg <- rast(weather, subds = "tavg")
pr <- rast(weather, subds = "pr")

yrs_t <- tapp(tavg, format(time(tavg), "%Y"), fun = mean, na.rm = TRUE)
yrs_p <- format(time(pr),   "%Y")

```

```{r}


NAflag(tasmax) <- -3.4e+38

# annual means: 24837 layers -> 68
yr <- tapp(tasmax, format(time(tasmax), "%Y"), fun = mean, na.rm = TRUE)
names(yr) <- sub("^X", "", names(yr))    # tapp prefixes with X

#fine <- focal(fine, w = 5, fun = mean, na.rm = TRUE)
writeRaster(yr, "~/FishyG/data/Global_weather/tasmax_annual.tif", overwrite = TRUE)

tmax <- rast("~/FishyG/data/Global_weather/tasmax_annual.tif")
years <- names(tmax)


```

```{r}
pal <- colorFactor(c("#1b9e77", "#7570b3", "darkgrey"), domain = river_coords$model)

pal_t <- colorNumeric("RdYlBu", values(tmax), na.color = "transparent",
                      reverse = TRUE)
```

```{r}
#crs(weather_raster) <- "EPSG:4326"                        # if missing
#weather_raster <- rotate(weather_raster)                               # if longitudes are 0–360
#weather_raster <- crop(weather_raster, ext(-135, -120, 47, 56))        # your area only
#weather_raster <- aggregate(weather_raster, fact = 2)                  # halve resolution

#pal_r <- colorNumeric("YlOrRd", values(weather_raster), na.color = "transparent")

```

The `echo: false` option disables the printing of code (only output is displayed).

```{r}

ui <- fluidPage(
  leafletOutput("map", height = 600),
  absolutePanel(
    bottom = 120, left = 30, width = 250,
    draggable = TRUE,
    style = "background: rgba(255,255,255,0.9); padding: 12px;
             border-radius: 5px; box-shadow: 0 0 8px rgba(0,0,0,0.2);",
    titlePanel("Site Map"),
    checkboxGroupInput("model", "Model:",
                         choices = sort(unique(river_coords$model)),
                         selected = unique(river_coords$model)),
    hr(),
  checkboxInput("show_temp", "Show temperature", TRUE),
    sliderInput("year", "Year:",
              min = as.numeric(min(years)),
              max = as.numeric(max(years)),
              value = 2012, step = 1, sep = "",
              animate = animationOptions(interval = 600, loop = TRUE))
    )
  )


server <- function(input, output, session) {
  
  filtered <- reactive({
    river_coords[river_coords$model %in% input$model, ]
  })
  
  output$map <- renderLeaflet({
    leaflet() %>% 
      addProviderTiles(providers$OpenStreetMap, group = "Street") %>%
    addProviderTiles(providers$Esri.WorldImagery, group = "Satellite") %>%
      fitBounds(min(river_coords$longitude), min(river_coords$latitude), max(river_coords$longitude), max(river_coords$latitude)) %>%
      addLayersControl(baseGroups = c("Street", "Satellite"),
                     overlayGroups = c("Temperature", "Sites"),
                     options = layersControlOptions(collapsed = FALSE))
    
  })
  #addRasterImage(tasmaxraster[[1]], colors = pal_r, opacity = 0.7, group = "tasmax")
  
  
  observe({
      proxy <- leafletProxy("map") %>% clearGroup("Temperature")
      req(input$show_temp)
      
      idx <- which(years == as.character(input$year))
      req(length(idx) > 0)

      proxy %>%
      addRasterImage(tmax[[idx]], colors = pal_t, opacity = 0.6,
                   group = "Temperature", project = FALSE,
                   method = "bilinear") 
      
  })

  observe({
      leafletProxy("map", data = filtered()) %>%
      clearGroup("stream_name_pse") %>%
      addCircleMarkers(~longitude, ~latitude,
                   group = "stream_name_pse",
                   fillColor = ~pal(model),
                   fillOpacity = 0.9,
                   stroke = FALSE,
                   radius = 6,
                   popup = ~paste0("<b>", stream_name_pse, "</b><br>Model: ", model))
  })
  
}

shinyApp(ui, server)
```

```{r}

ui <- fluidPage(
  leafletOutput("map", height = 600),
  absolutePanel(
    bottom = 120, left = 30, width = 250,
    draggable = TRUE,
    style = "background: rgba(255,255,255,0.9); padding: 12px;
             border-radius: 5px; box-shadow: 0 0 8px rgba(0,0,0,0.2);",
    titlePanel("Site Map"),
    checkboxGroupInput("model", "Model:",
                         choices = sort(unique(river_coords$model)),
                         selected = unique(river_coords$model)),
    hr(),
  checkboxInput("show_temp", "Show temperature", TRUE),
    sliderInput("year", "Year:",
              min = as.numeric(min(years)),
              max = as.numeric(max(years)),
              value = 2012, step = 1, sep = "",
              animate = animationOptions(interval = 600, loop = TRUE))
    )
  )


server <- function(input, output, session) {
  
  filtered <- reactive({
    river_coords[river_coords$model %in% input$model, ]
  })
  
  output$map <- renderLeaflet({
    leaflet() %>% 
      addProviderTiles(providers$OpenStreetMap, group = "Street") %>%
    addProviderTiles(providers$Esri.WorldImagery, group = "Satellite") %>%
      fitBounds(min(river_coords$longitude), min(river_coords$latitude), max(river_coords$longitude), max(river_coords$latitude)) %>%
      addLayersControl(baseGroups = c("Street", "Satellite"),
                     overlayGroups = c("Temperature", "Sites"),
                     options = layersControlOptions(collapsed = FALSE))
    
  })
  #addRasterImage(tasmaxraster[[1]], colors = pal_r, opacity = 0.7, group = "tasmax")
  
  
  observe({
      leafletProxy("map", data = filtered()) %>%
      clearGroup("stream_name_pse") %>%
     addCircleMarkers(~longitude, ~latitude,
                   group = "stream_name_pse",
                   fillColor = ~pal(model),
                   fillOpacity = 0.9,
                   stroke = FALSE,
                   radius = 6,
                   popup = ~paste0("<b>", stream_name_pse, "</b><br>Model: ", model))
  })
  
}

shinyApp(ui, server)
```
